import {strict as assert} from 'node:assert';
import {bracket,decodeFrame,mixBodies,followBox} from '../demo/web/tracking-math.js';
assert.equal(bracket([],1),null);
for(const [time,want] of [[-1,[0,1,0]],[0,[0,1,0]],[.05,[0,1,.5]],[.1,[1,2,0]],[.15,[1,2,.4999999999999999]],[9,[2,2,0]]])assert.deepEqual(bracket([{time:0},{time:.1},{time:.2}],time),want);
const n=18439*3+127*3+3,size=16+4*n;
const data=new ArrayBuffer(size+36874*3*4),view=new DataView(data);new Uint8Array(data,0,8).set(new TextEncoder().encode('S3DTRK01'));view.setFloat64(8,1.25,true);
for(let i=0;i<n;i++)view.setFloat32(16+i*4,(i%10)/10,true);
const a=decodeFrame(data);assert.equal(a.time,1.25);assert.equal(a.body.tensors.vertices.length,55317);
assert.equal(decodeFrame(data.slice(0,size),a.body.faces).time,1.25);
assert.throws(()=>decodeFrame(data.slice(0,size)));
assert.throws(()=>decodeFrame(data.slice(0,30)));
view.setFloat32(16,NaN,true);assert.throws(()=>decodeFrame(data));view.setFloat32(16,101,true);assert.throws(()=>decodeFrame(data));view.setFloat32(16,0,true);
view.setUint32(size,18439,true);assert.throws(()=>decodeFrame(data));view.setUint32(size,0,true);
const b=decodeFrame(data).body;for(const key of Object.keys(b.tensors))b.tensors[key]=b.tensors[key].map(x=>x+1);
const out={tensors:{}};mixBodies(a.body,b,.5,out);
for(const key of Object.keys(out.tensors))for(let i=0;i<out.tensors[key].length;i++)assert.ok(Math.abs(out.tensors[key][i]-a.body.tensors[key][i]-.5)<1e-6);
assert.throws(()=>mixBodies(a.body,b,NaN,out));assert.throws(()=>mixBodies(a.body,b,1.1,out));
const s={box:[0,0,960,720],camera:[1000,1000,480,360]};
const followed=followBox(a.body,s,960,720);assert.ok(followed.box.every((v,i)=>Number.isFinite(v)&&Math.abs(v-s.box[i])<=(i%2?720:960)*.05));
console.log('Tracking interpolation, binary validation, clamp/no-extrapolation and crop tests passed.');
const sk=new ArrayBuffer(16+(127*8+3)*4),sv=new DataView(sk);new Uint8Array(sk,0,8).set(new TextEncoder().encode('S3DSKL01'));sv.setFloat64(8,.17,true);
for(let j=0;j<127;j++){sv.setFloat32(16+(j*8)*4,100,true);sv.setFloat32(16+(j*8+1)*4,200,true);sv.setFloat32(16+(j*8+6)*4,1,true);sv.setFloat32(16+(j*8+7)*4,1,true)}
const skeleton=decodeFrame(sk);assert.equal(skeleton.time,.17);assert.equal(skeleton.body.schema,'sam3d.body.skeleton.v1');assert.equal(skeleton.body.tensors.vertices.length,0);assert.deepEqual([...skeleton.body.tensors.joints.slice(0,3)],[1,-2,-0]);
sv.setFloat32(16+7*4,0,true);assert.throws(()=>decodeFrame(sk));sv.setFloat32(16+7*4,1,true);sv.setFloat32(16+6*4,0,true);assert.throws(()=>decodeFrame(sk));
console.log('Skeleton-only playback decoding and transform validation passed.');
